"""Evidence-backed, directly reusable PoC bundles for Muteki runs.

The bundle is a read-only materialization of the canonical Muteki trace.  It
never invents a request from a flag or a prose conclusion: every executable
step must come from a completed HTTP ToolCall and have a corresponding
EvidenceLedger reference.
"""

from __future__ import annotations

import asyncio
import io
import json
import re
import zipfile
from dataclasses import dataclass
from typing import Any, Mapping, Sequence

from app.services.muteki_recovered_trace import load_recovered_trace


class PocBundleUnavailable(ValueError):
    """Raised when a solved run has no safe, evidence-backed request plan."""


@dataclass(frozen=True, slots=True)
class PocBundle:
    """Serialized PoC package and its auditable plan metadata."""

    filename: str
    content: bytes
    request_plan: tuple[dict[str, Any], ...]
    evidence_refs: tuple[str, ...]


_HTTP_TOOLS = frozenset({"http_request", "http_session_request"})
_SENSITIVE_KEY = re.compile(r"(?i)(password|passwd|secret|token|api[_-]?key|authorization|cookie)")
_FLAG_PATTERN = re.compile(r"flag\{[^{}\r\n]*\}", re.IGNORECASE)


def _value(item: Any, name: str, default: Any = None) -> Any:
    if isinstance(item, Mapping):
        return item.get(name, default)
    return getattr(item, name, default)


def _safe_value(value: Any, *, key: str = "") -> Any:
    if _SENSITIVE_KEY.search(key):
        return "{{secret_value}}"
    if isinstance(value, Mapping):
        return {str(k): _safe_value(v, key=str(k)) for k, v in value.items()}
    if isinstance(value, list):
        return [_safe_value(item, key=key) for item in value[:50]]
    if isinstance(value, str):
        return _FLAG_PATTERN.sub("{{flag_pattern_match}}", value[:4000])
    return value


def _step_plan(
    steps: Sequence[Any],
    *,
    evidence_by_tool_call: Mapping[str, Sequence[str]],
    evidence_by_artifact: Mapping[str, Sequence[str]],
) -> list[dict[str, Any]]:
    plan: list[dict[str, Any]] = []
    for item in steps:
        tool = str(_value(item, "tool_name", "") or "")
        if tool not in _HTTP_TOOLS:
            continue
        arguments = _value(item, "normalized_arguments", {})
        if not isinstance(arguments, Mapping) or not arguments.get("url"):
            continue
        call_ids = [str(value) for value in (_value(item, "source_tool_call_ids", []) or []) if value]
        artifact_ids = [str(value) for value in (_value(item, "source_artifact_ids", []) or []) if value]
        refs: list[str] = []
        for call_id in call_ids:
            refs.extend(str(ref) for ref in evidence_by_tool_call.get(call_id, ()) if ref)
        for artifact_id in artifact_ids:
            refs.extend(str(ref) for ref in evidence_by_artifact.get(artifact_id, ()) if ref)
        refs = list(dict.fromkeys(refs))
        # An executable request without durable evidence is not an exportable
        # PoC.  It may remain in the report as an attempted route.
        if not refs:
            continue
        plan.append(
            {
                "order": int(_value(item, "order", len(plan) + 1) or len(plan) + 1),
                "title": str(_value(item, "title_zh", "验证 HTTP 请求") or "验证 HTTP 请求"),
                "purpose": str(_value(item, "purpose_zh", "复现已验证路线") or "复现已验证路线")[:1000],
                "tool": tool,
                "arguments": _safe_value(dict(arguments)),
                "expected_status": _value(item, "expected_status"),
                "expected_evidence": [str(value) for value in (_value(item, "expected_evidence", []) or [])[:10]],
                "evidence_refs": refs[:32],
                "source_tool_call_ids": call_ids[:16],
            }
        )
    return plan


def _runtime_script() -> str:
    return r'''#!/usr/bin/env python3
"""Generated by Muteki from an evidence-backed request plan.

Only the target and optional secrets are supplied at runtime.  The script
prints status/digest/flag-pattern matches, never a raw response body.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from http.cookiejar import CookieJar

FLAG_PATTERN = re.compile(os.environ.get("FLAG_PATTERN", r"flag\{[^}]+\}"), re.I)
TARGET_URL = os.environ.get("TARGET_URL", "").strip().rstrip("/")
SESSION_COOKIE = os.environ.get("SESSION_COOKIE", "").strip()


def resolve(value, key="", context=None):
    context = context or {}
    if isinstance(value, dict):
        return {str(k): resolve(v, str(k), context) for k, v in value.items()}
    if isinstance(value, list):
        return [resolve(item, key, context) for item in value]
    if not isinstance(value, str):
        return value
    if value == "{{target_url}}":
        if not TARGET_URL:
            raise RuntimeError("TARGET_URL is required")
        return TARGET_URL
    if value.startswith("{{target_url}}"):
        if not TARGET_URL:
            raise RuntimeError("TARGET_URL is required")
        return TARGET_URL + value[len("{{target_url}}"):]
    if value == "{{target_host}}":
        return urllib.parse.urlsplit(TARGET_URL).netloc
    if value.startswith("{{previous:") and value.endswith("}}"):
        name = value[len("{{previous:"):-2].strip()
        resolved = context.get(name)
        if not resolved:
            raise RuntimeError("previous response value is unavailable: " + name)
        return resolved
    if value == "{{secret_value}}":
        if "cookie" in key.lower():
            return SESSION_COOKIE
        env_name = "POC_" + re.sub(r"[^A-Za-z0-9]+", "_", key).strip("_").upper()
        return os.environ.get(env_name) or os.environ.get("POC_SECRET_VALUE", "")
    return value


def request_one(item, opener, context):
    arguments = resolve(item.get("arguments") or {}, context=context)
    url = str(arguments.get("url") or "")
    if url.startswith("/"):
        url = urllib.parse.urljoin(TARGET_URL.rstrip("/") + "/", url.lstrip("/"))
    if not url:
        raise RuntimeError("request plan contains no URL")
    query = arguments.get("query")
    if isinstance(query, dict) and query:
        encoded = urllib.parse.urlencode(query, doseq=True)
        url += ("&" if "?" in url else "?") + encoded
    headers = {str(k): str(v) for k, v in (arguments.get("headers") or {}).items()}
    if SESSION_COOKIE and not any(str(k).lower() == "cookie" for k in headers):
        headers["Cookie"] = SESSION_COOKIE
    body = arguments.get("json")
    if isinstance(body, dict):
        data = json.dumps(body, ensure_ascii=False).encode("utf-8")
        headers.setdefault("Content-Type", "application/json")
    else:
        form = arguments.get("form")
        body = form if isinstance(form, dict) else arguments.get("body")
        if isinstance(body, dict):
            data = urllib.parse.urlencode(body, doseq=True).encode("utf-8")
            headers.setdefault("Content-Type", "application/x-www-form-urlencoded")
        elif body in (None, ""):
            data = None
        else:
            data = str(body).encode("utf-8")
    method = str(arguments.get("method") or "GET").upper()
    request = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with opener.open(request, timeout=float(os.environ.get("POC_TIMEOUT", "20"))) as response:
            raw = response.read()
            status = int(response.status)
    except urllib.error.HTTPError as error:
        raw = error.read()
        status = int(error.code)
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8", errors="replace")
    matches = list(dict.fromkeys(FLAG_PATTERN.findall(text)))
    expected = item.get("expected_status")
    ok = expected is None or int(expected) == status
    extraction = item.get("arguments", {}).get("extract_json_path")
    if isinstance(extraction, dict) and extraction.get("save_as") and extraction.get("path"):
        try:
            extracted: object = json.loads(text)
            for part in str(extraction["path"]).split("."):
                extracted = extracted[part] if isinstance(extracted, dict) else None
            if extracted not in (None, ""):
                context[str(extraction["save_as"])] = str(extracted)
        except (TypeError, ValueError, KeyError, json.JSONDecodeError):
            pass
    return {"order": item.get("order"), "tool": item.get("tool"), "status": status,
            "body_length": len(raw), "sha256": digest, "flag_matches": matches[:10],
            "expected_status": expected, "ok": ok}


def main():
    if not TARGET_URL:
        print(json.dumps({"ok": False, "error": "TARGET_URL is required"}))
        return 2
    with open(os.path.join(os.path.dirname(__file__), "request-plan.json"), encoding="utf-8") as handle:
        plan = json.load(handle)
    if not plan:
        print(json.dumps({"ok": False, "error": "NO_EXECUTABLE_REQUEST_PLAN"}))
        return 3
    jar = CookieJar()
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))
    results = []
    context = {}
    for item in plan:
        try:
            results.append(request_one(item, opener, context))
        except Exception as error:
            results.append({"order": item.get("order"), "tool": item.get("tool"), "ok": False,
                            "error": type(error).__name__})
    output = {"ok": all(bool(item.get("ok")) for item in results), "steps": results}
    print(json.dumps(output, ensure_ascii=False, indent=2))
    return 0 if output["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
'''


def build_poc_bundle(
    *,
    run_id: str,
    challenge_name: str,
    steps: Sequence[Any],
    evidence_by_tool_call: Mapping[str, Sequence[str]],
    evidence_by_artifact: Mapping[str, Sequence[str]],
    graph_pocs: Sequence[Mapping[str, Any]] = (),
) -> PocBundle:
    """Build a zip only from completed, evidence-linked HTTP requests."""

    plan = _step_plan(
        steps,
        evidence_by_tool_call=evidence_by_tool_call,
        evidence_by_artifact=evidence_by_artifact,
    )
    if not plan:
        raise PocBundleUnavailable(
            "MUTEKI_POC_NOT_REPRODUCIBLE: no completed HTTP request has a durable Evidence reference"
        )
    refs = tuple(dict.fromkeys(ref for item in plan for ref in item["evidence_refs"]))
    manifest = {
        "format": "muteki-poc-bundle/v1",
        "run_id": str(run_id),
        "challenge": str(challenge_name)[:200],
        "evidence_refs": list(refs),
        "steps": [
            {
                "order": item["order"],
                "tool": item["tool"],
                "evidence_refs": item["evidence_refs"],
                "source_tool_call_ids": item["source_tool_call_ids"],
            }
            for item in plan
        ],
        "evidence_sources": (
            ["recovered_execution_record"]
            if any(str(ref).startswith("recovered:") for ref in refs)
            else ["evidence_ledger"]
        ),
    }
    notes = [
        "# 可复现攻击 PoC",
        "",
        "本包由 Muteki SharedGraph / ToolCall / EvidenceLedger 只读物化生成。",
        "每个请求步骤都关联了已持久化的 Evidence 引用；脚本不会把 Flag 写死。",
        "",
        "## 使用",
        "",
        "```bash",
        "export TARGET_URL='http://authorized-target.example'",
        "# 如请求需要会话：export SESSION_COOKIE='name=value'",
        "python reproduce.py",
        "```",
        "",
        f"- Run: `{run_id}`",
        f"- 题目: {challenge_name}",
        f"- 可执行请求数: {len(plan)}",
        f"- Evidence 数: {len(refs)}",
        "- 原始响应、Token、密码和 Cookie 不会写入包；敏感字段通过环境变量提供。",
        "",
        "## 请求步骤",
    ]
    for item in plan:
        notes.extend(
            [
                f"### {item['order']}. {item['title']}",
                f"- 目的：{item['purpose']}",
                f"- 工具：`{item['tool']}`",
                f"- Evidence：{', '.join(f'`{ref}`' for ref in item['evidence_refs'])}",
                "",
            ]
        )
    if graph_pocs:
        notes.extend(["## Graph PoC 记录", ""])
        for poc in graph_pocs[:20]:
            notes.append(
                f"- `{str(poc.get('poc_id') or poc.get('name') or 'poc')[:120]}` · "
                f"status={str(poc.get('status') or 'available')[:40]} · "
                f"artifact={str(poc.get('artifact_id') or 'n/a')[:120]}"
            )
    files = {
        "README.zh-CN.md": "\n".join(notes) + "\n",
        "reproduce.py": _runtime_script(),
        "request-plan.json": json.dumps(plan, ensure_ascii=False, indent=2),
        "evidence-manifest.json": json.dumps(manifest, ensure_ascii=False, indent=2),
        "requirements.txt": "# Python standard library only\n",
    }
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path, content in files.items():
            archive.writestr(path, content.encode("utf-8"))
    return PocBundle(
        filename=f"muteki-{run_id}-poc.zip",
        content=buffer.getvalue(),
        request_plan=tuple(plan),
        evidence_refs=refs,
    )


async def build_poc_bundle_for_run(session: Any, run: Any, challenge: Any, graph_state: Mapping[str, Any]) -> PocBundle:
    """Collect the existing trace and build a bundle without a new model call."""

    # Imported lazily to keep report/poc services acyclic.
    from sqlalchemy import select

    from app.models.multi_agent import EvidenceLedger
    from app.models.run import Artifact, ToolCall
    from app.services.reports import ReproductionPlanner

    steps = await ReproductionPlanner().plan(session, run, challenge)
    call_ids = {
        str(call_id)
        for step in steps
        for call_id in (_value(step, "source_tool_call_ids", []) or [])
        if call_id
    }
    artifact_ids = {
        str(artifact_id)
        for step in steps
        for artifact_id in (_value(step, "source_artifact_ids", []) or [])
        if artifact_id
    }
    ledgers = list(
        (
            await session.scalars(
                select(EvidenceLedger).where(
                    EvidenceLedger.run_id == str(run.id),
                    (EvidenceLedger.tool_call_id.in_(call_ids) if call_ids else EvidenceLedger.id == ""),
                )
            )
        ).all()
    )
    artifact_ledgers = list(
        (
            await session.scalars(
                select(EvidenceLedger).where(
                    EvidenceLedger.run_id == str(run.id),
                    (EvidenceLedger.artifact_id.in_(artifact_ids) if artifact_ids else EvidenceLedger.id == ""),
                )
            )
        ).all()
    )
    # Keep the imports above explicit: these references document that the
    # plan is derived from persisted ToolCall/Artifact rows, not model prose.
    _ = ToolCall, Artifact
    by_call: dict[str, list[str]] = {}
    by_artifact: dict[str, list[str]] = {}
    for ledger in ledgers:
        if str(ledger.status or "").upper() == "VERIFIED" and ledger.tool_call_id:
            by_call.setdefault(str(ledger.tool_call_id), []).append(str(ledger.id))
    for ledger in artifact_ledgers:
        if str(ledger.status or "").upper() == "VERIFIED" and ledger.artifact_id:
            by_artifact.setdefault(str(ledger.artifact_id), []).append(str(ledger.id))
    try:
        return build_poc_bundle(
            run_id=str(run.id),
            challenge_name=str(getattr(challenge, "name", "") or ""),
            steps=steps,
            evidence_by_tool_call=by_call,
            evidence_by_artifact=by_artifact,
            graph_pocs=graph_state.get("pocs", ()) if isinstance(graph_state, Mapping) else (),
        )
    except PocBundleUnavailable:
        # The native Muteki Worker may have a complete, digest-addressed
        # execution record while the legacy ORM projection has no HTTP rows.
        # Recover only from that immutable Run-local record; never infer a
        # request from a flag, prose, or a Blackboard conclusion.
        trace = await asyncio.to_thread(
            load_recovered_trace,
            workspace=str(getattr(run, "workspace_path", "") or ""),
            target_url=str(getattr(challenge, "target_url", "") or ""),
        )
        replayable = trace.get("replayable_steps", []) if trace.get("available") else []
        if not replayable:
            raise
        recovered_refs = {
            str(ref): [str(ref)]
            for item in trace.get("evidence", [])
            for ref in [item.get("id")]
            if ref and str(item.get("status") or "").upper() == "VERIFIED"
        }
        return build_poc_bundle(
            run_id=str(run.id),
            challenge_name=str(getattr(challenge, "name", "") or ""),
            steps=replayable,
            evidence_by_tool_call={},
            evidence_by_artifact=recovered_refs,
            graph_pocs=graph_state.get("pocs", ()) if isinstance(graph_state, Mapping) else (),
        )


__all__ = ["PocBundle", "PocBundleUnavailable", "build_poc_bundle", "build_poc_bundle_for_run"]
