export interface Challenge { id: string; name: string; description: string; challenge_type: "WEB_TARGET" | "TRAFFIC_ANALYSIS"; target_url?: string | null; allowed_hosts: string[]; flag_pattern: string; source_path?: string | null; status: string; primary_attachment_id?: string | null; metadata_json?: Record<string, unknown>; run_count?: number; solved_run_count?: number; latest_run_status?: string | null; latest_run_started_at?: string | null; latest_run_engine_type?: string | null; created_at: string; updated_at: string }
export interface Skill { id: string; name: string; display_name: string; description: string; source_type: "BUILTIN" | "CUSTOM"; skill_kind: "CORE" | "METHODOLOGY" | "SPECIALIST"; activation_mode: "ALWAYS" | "AUTO" | "MANUAL"; triggers: string[]; negative_triggers?: string[]; prerequisites: string[]; required_tools: string[]; recommended_tools: string[]; forbidden_tools: string[]; ctf_phases: string[]; challenge_types: string[]; content_markdown: string; allowed_tools: string[]; risk_level: string; version: number; enabled: boolean; catalog_scope?: string; binding_count: number; created_at: string; updated_at: string }
export interface ChallengeConversation { id: string; challenge_id: string; model_config_id?: string | null; title: string; status: string; created_at: string; updated_at: string }
export interface ChallengeMessage { id: string; conversation_id: string; role: "user" | "assistant" | "system"; content: string; status: string; error_message?: string | null; created_at: string }
export type SolverMode = "single_agent" | "multi_agent_v1" | "solver_v2" | "muteki";
export interface WorkerEngineSelection { engine_type: "mock" | "codex_sdk" | "openai_compatible"; engine_id?: string; model_config_id?: string | null }
export interface ModelConfig { id: string; name: string; provider_type: string; base_url?: string; model_name?: string; enabled: boolean; api_key_configured: boolean; roles?: Array<"worker" | "coordinator_reason">; action_protocol?: string; structured_output_mode?: string; request_timeout_seconds?: number; max_output_tokens?: number; temperature?: number; max_retries?: number; retry_base_seconds?: number; rate_limit_cooldown_seconds?: number; requests_per_minute?: number; max_concurrency?: number; context_token_limit?: number; capabilities?: Record<string, unknown>; last_test_at?: string | null; last_test_ok?: boolean | null }
export interface SolveRun { id: string; challenge_id: string; challenge_name?: string | null; title?: string | null; challenge_type?: string | null; target_summary?: string | null; engine_type: string; solver_mode: SolverMode; model_config_id?: string | null; model_name?: string | null; reason_model_config_id?: string | null; reason_model_name?: string | null; worker_engines?: WorkerEngineSelection[]; role_name?: string | null; role_version?: string | null; role_snapshot_json: Record<string, unknown>; status: string; current_phase: string; workspace_path: string; max_agent_steps: number; max_tool_calls: number; max_context_observations: number; max_runtime_seconds: number; max_total_runtime_seconds?: number; agent_checkpoint_interval?: number; context_revision?: number; infrastructure_retry_count?: number; agent_step_count: number; tool_call_count: number; run_total_agent_steps?: number; run_total_logical_tool_calls?: number; attempt_agent_steps?: number; attempt_logical_tool_calls?: number; checkpoint_segment_steps?: number; current_attempt_number?: number; last_error_code?: string | null; last_error_message?: string | null; active_skill_names?: string[]; diagnostic_tags?: string[]; diagnostic_summary?: string | null; started_at?: string | null; finished_at?: string | null; created_at: string; updated_at: string }
export interface FlagCandidate { id: string; candidate: string; verified: boolean; review_state: "OPEN" | "VALID" | "INVALID"; pattern_matched: boolean }
export interface RunEvent { id: string; run_id: string; sequence: number; event_type: string; payload_json: Record<string, unknown>; created_at: string }
export interface RunUsageRow { model: string; role: string; source: string; calls: number; input_tokens: number; output_tokens: number; total_tokens: number; cost_usd: number }
export interface RunUsage { total: RunUsageRow; models: RunUsageRow[] }
export interface MutekiBoardSemantic { status: "idle" | "running" | "completed" | "failed"; model?: string; revision?: number; fingerprint?: string; items?: Array<{ card_id: string; summary_zh: string; category: string; importance: "high" | "medium" | "low" }>; usage?: { input_tokens?: number; output_tokens?: number; total_tokens?: number }; error_code?: string; updated_at?: string }
export interface MutekiGraphState { available: boolean; run_id: string; revision: number; facts: Array<{ sequence: number; content: string; verified: boolean; evidence_refs: string[]; source_worker_id?: string; created_at?: string }>; key_conditions?: Array<{ sequence: number; content: string; summary_zh: string; verified: boolean; evidence_refs: string[]; confidence?: number; source_worker_id?: string }>; board_semantic?: MutekiBoardSemantic; intents: Array<{ id: string; description: string; status: "open" | "claimed" | "done"; worker?: string | null; result?: string; sequence?: number }>; dead_ends: Array<{ sequence: number; description: string }>; flags: Array<{ sequence: number; flag: string; verified: boolean; evidence_refs: string[] }>; pocs?: Array<{ poc_id: string; name?: string; path?: string; entry_command?: string; status?: string; note?: string; artifact_id?: string }>; reason?: string }
export interface RunUserInput { id: string; content: string; input_type: string; status: string; revision: number; created_at: string; consumed_at?: string | null }
export interface SolverState { id: string; run_id: string; current_phase: string; confirmed_facts_json: Record<string, unknown>[]; rejected_paths_json: Record<string, unknown>[]; active_hypotheses_json: Record<string, unknown>[]; action_fingerprints_json: Record<string, unknown>; active_skill_ids_json: string[]; skill_recommendations_json: Record<string, unknown>[]; run_plan_json?: Record<string, unknown>; capability_ledger_json?: Record<string, unknown>; read_files_json?: string[]; read_ranges_json?: Record<string, unknown>[]; last_decision_card_json?: Record<string, unknown>; last_experiment_json?: Record<string, unknown>; no_progress_count: number; last_progress_at?: string | null; created_at: string; updated_at: string }
export interface RunDiagnosticAnomaly { code: string; severity: string; title: string; summary: string; evidence: string[]; suggestion: string }
export interface RunDiagnostics { diagnostic_tags: string[]; diagnostic_summary?: string | null; anomalies: RunDiagnosticAnomaly[]; state: { current_phase: string; no_progress_count: number; active_skill_names: string[]; recommended_skills: Record<string, unknown>[] }; challenge: { name?: string | null; challenge_type?: string | null; target_summary?: string | null }; engine: { engine_type: string; model_name?: string | null } }
export interface RunHealth {
  status: string;
  current_phase: string;
  last_error_code?: string | null;
  runtime: { active_lease: boolean; lease_owner?: string | null; running_task: boolean; running_tool: boolean };
  input: { queued: number; consumed: number };
  progress: { last_fact?: string | null; last_tool?: string | null; last_tool_status?: string | null; no_progress_count: number };
  next_action: string;
  checkpoint: Record<string, unknown>;
}
export interface ApiEnvelope<T> { data: T }
