export interface Challenge { id: string; name: string; description: string; challenge_type: "WEB_TARGET" | "TRAFFIC_ANALYSIS"; target_url?: string | null; allowed_hosts: string[]; flag_pattern: string; source_path?: string | null; status: string; primary_attachment_id?: string | null; metadata_json?: Record<string, unknown>; run_count?: number; solved_run_count?: number; latest_run_status?: string | null; latest_run_started_at?: string | null; latest_run_engine_type?: string | null; created_at: string; updated_at: string }
export interface Skill { id: string; name: string; display_name: string; description: string; source_type: "BUILTIN" | "CUSTOM"; skill_kind: "CORE" | "METHODOLOGY" | "SPECIALIST"; activation_mode: "ALWAYS" | "AUTO" | "MANUAL"; triggers: string[]; negative_triggers?: string[]; prerequisites: string[]; required_tools: string[]; recommended_tools: string[]; forbidden_tools: string[]; ctf_phases: string[]; challenge_types: string[]; content_markdown: string; allowed_tools: string[]; risk_level: string; version: number; enabled: boolean; catalog_scope?: string; binding_count: number; created_at: string; updated_at: string }
export interface ChallengeConversation { id: string; challenge_id: string; model_config_id?: string | null; title: string; status: string; created_at: string; updated_at: string }
export interface ChallengeMessage { id: string; conversation_id: string; role: "user" | "assistant" | "system"; content: string; status: string; error_message?: string | null; created_at: string }
export interface SolveRun { id: string; challenge_id: string; challenge_name?: string | null; challenge_type?: string | null; target_summary?: string | null; engine_type: string; model_config_id?: string | null; model_name?: string | null; role_name?: string | null; role_version?: string | null; role_snapshot_json: Record<string, unknown>; status: string; current_phase: string; workspace_path: string; max_agent_steps: number; max_tool_calls: number; max_context_observations: number; max_runtime_seconds: number; agent_step_count: number; tool_call_count: number; last_error_code?: string | null; last_error_message?: string | null; active_skill_names?: string[]; diagnostic_tags?: string[]; diagnostic_summary?: string | null; started_at?: string | null; finished_at?: string | null; created_at: string; updated_at: string }
export interface FlagCandidate { id: string; candidate: string; verified: boolean; review_state: "OPEN" | "VALID" | "INVALID"; pattern_matched: boolean }
export interface RunEvent { id: string; run_id: string; sequence: number; event_type: string; payload_json: Record<string, unknown>; created_at: string }
export interface SolverState { id: string; run_id: string; current_phase: string; confirmed_facts_json: Record<string, unknown>[]; rejected_paths_json: Record<string, unknown>[]; active_hypotheses_json: Record<string, unknown>[]; action_fingerprints_json: Record<string, unknown>; active_skill_ids_json: string[]; skill_recommendations_json: Record<string, unknown>[]; no_progress_count: number; last_progress_at?: string | null; created_at: string; updated_at: string }
export interface RunDiagnosticAnomaly { code: string; severity: string; title: string; summary: string; evidence: string[]; suggestion: string }
export interface RunDiagnostics { diagnostic_tags: string[]; diagnostic_summary?: string | null; anomalies: RunDiagnosticAnomaly[]; state: { current_phase: string; no_progress_count: number; active_skill_names: string[]; recommended_skills: Record<string, unknown>[] }; challenge: { name?: string | null; challenge_type?: string | null; target_summary?: string | null }; engine: { engine_type: string; model_name?: string | null } }
export interface ApiEnvelope<T> { data: T }
