import { CopyOutlined, PlusOutlined } from "@ant-design/icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Card, message, Space, Table, Tag } from "antd";
import { useState } from "react";
import { SkillEditor } from "../components/skills/SkillEditor";
import { api } from "../services/api";
import type { Skill } from "../types/api";

export function SkillsPage() {
  const client = useQueryClient(); const [editing, setEditing] = useState<Skill>(); const [open, setOpen] = useState(false);
  const query = useQuery({ queryKey: ["skills"], queryFn: api.listSkills });
  const save = useMutation({ mutationFn: async (payload: Record<string, unknown>) => { if (editing) await api.validateSkill(editing.id); return editing ? api.updateSkill(editing.id, payload) : api.createSkill(payload); }, onSuccess: () => { void client.invalidateQueries({ queryKey: ["skills"] }); setOpen(false); message.success("Skill 已保存"); }, onError: (error: Error) => message.error(error.message) });
  const duplicate = useMutation({ mutationFn: api.duplicateSkill, onSuccess: () => { void client.invalidateQueries({ queryKey: ["skills"] }); message.success("已创建自定义副本"); }, onError: (error: Error) => message.error(error.message) });
  return <><div className="page-heading"><div><h1>Skills 管理</h1><p>为模型和题目配置可审计、不可扩大权限的解题工作流。</p></div><Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditing(undefined); setOpen(true); }}>新建 Skill</Button></div><Card className="panel-card"><Table rowKey="id" loading={query.isLoading} dataSource={query.data} columns={[{ title: "名称", render: (_, row: Skill) => <Space><strong>{row.display_name}</strong>{row.source_type === "BUILTIN" && <Tag color="cyan">内置</Tag>}</Space> }, { title: "分类", dataIndex: "skill_kind", render: (value: string) => <Tag color={value === "CORE" ? "geekblue" : value === "METHODOLOGY" ? "cyan" : "default"}>{value}</Tag> }, { title: "激活", dataIndex: "activation_mode", render: (value: string) => <Tag color={value === "ALWAYS" ? "success" : value === "AUTO" ? "processing" : "default"}>{value}</Tag> }, { title: "适用题型", dataIndex: "challenge_types", render: (types: string[]) => types.map(type => <Tag key={type}>{type === "WEB_TARGET" ? "Web" : "流量"}</Tag>) }, { title: "版本", dataIndex: "version" }, { title: "风险", dataIndex: "risk_level" }, { title: "状态", dataIndex: "enabled", render: (value: boolean) => <Tag color={value ? "success" : "default"}>{value ? "启用" : "停用"}</Tag> }, { title: "绑定模型", dataIndex: "binding_count" }, { title: "更新时间", dataIndex: "updated_at", render: (value: string) => new Date(value).toLocaleString() }, { title: "操作", render: (_, row: Skill) => <Space><Button type="link" onClick={() => { setEditing(row); setOpen(true); }}>{row.source_type === "BUILTIN" ? "查看" : "编辑"}</Button>{row.source_type === "BUILTIN" && <Button type="link" icon={<CopyOutlined />} onClick={() => duplicate.mutate(row.id)}>复制为自定义</Button>}</Space> }]} /></Card><SkillEditor open={open} value={editing} loading={save.isPending} onClose={() => setOpen(false)} onSave={value => save.mutate(value)} /></>;
}
